# Generated by Django 4.1.5 on 2023-01-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('text', models.CharField(max_length=45)),
                ('completed', models.BooleanField(default=False))
            ],
        ),
    ]
